//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using Repository.Pattern.Ef6;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SI_Category : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SI_Category()
        {
            this.SI_CategoryDetail = new HashSet<SI_CategoryDetail>();
        }
    
        public byte Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [JsonIgnore]
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SI_CategoryDetail> SI_CategoryDetail { get; set; }
    }
}
