//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using Repository.Pattern.Ef6;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SysGenCode : Entity
    {
        public string TableName { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> CurentDate { get; set; }
        public string FormatDate { get; set; }
        public int Length { get; set; }
        public int CurentIndex { get; set; }
        public string CurentAlphabet { get; set; }
        public bool UsingAlphabet { get; set; }
        public string TypeReset { get; set; }
        public string FormatCode { get; set; }
        public string FormatKey { get; set; }
    }
}
