//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using Repository.Pattern.Ef6;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SysLog : Entity
    {
        public string LogId { get; set; }
        public string UserChange { get; set; }
        public System.DateTime DateChange { get; set; }
        public string ChangeInfo { get; set; }
        public string LogInfo { get; set; }
    }
}
