//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using Repository.Pattern.Ef6;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenu : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysMenu()
        {
            this.SysMenu1 = new HashSet<SysMenu>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ActionCode { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Params { get; set; }
        public string Pram1 { get; set; }
        public string Pram2 { get; set; }
        public string Pram3 { get; set; }
        public string QuerryString { get; set; }
        public string Url { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Order { get; set; }
        public string Description { get; set; }
        public Nullable<int> MenuType { get; set; }
        public string Icon { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual SysAction SysAction { get; set; }
        [JsonIgnore]
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysMenu> SysMenu1 { get; set; }
        public virtual SysMenu SysMenu2 { get; set; }
    }
}
